travis:
  secure:
    BINSTAR_TOKEN: TTneMeIX4OOAeS8IJmNEaGIawxph7WrGHsNpHWkbEjo4vLIEgk10B/Qpd42J9ESzJ94I4/t/Nu7k1/2G9ruB3Yccc7FzbENOnXnDmppye6Vcy9IrQ7DwGyjc1/NwcYAdDKaxyCyTZoQXZ8R16A334Hcpb+gwolEAYTclFrZWNaU0dqF1QkfgOMc8wncoEtzFQSanCgY/1A0R/AiPECALLgjVeubIW4y3sMuZz+7XMhULWlbLzBj8beHm0ZUdepHsLrEJ/EL5thX1BriuIDSmq9cqaRyXYOhXaWHvi5+OEnkd12k+7xwnDGsr7CZcVZPgzYS0HR1bM6M7seIhtoKUdzSHhhFd7lRUgWzVj07L7QjesrVveeRdW5ooa+ORJJt0WwH+YAzHWfZKCCPGzg5z1i+FZ8q5V7aNIA9oM3K+aPccuKrCytaSvP8+GMVSgX5tUc9hZ6xDodiCJNdMTDUZaMS4JMuW7iA4TmeQw/KxV6zMsGR8EmgVpIERyR2Q/tcAksXG8A0OJDnVJmn872c68ukzai33z/hzTwHdOBlwz4SyQ9MfsVZVwvhg+B83saIB+sVGei9beF2o0xdpjIh0qonDkN6u1uoP+tzEro2AAuR9a2HR0KUH/MADF7P25HjewX8wRIeokt2Dc7V+m5bo5x+yScgdt0T62EWy07vfgzk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
