travis:
  secure:
    BINSTAR_TOKEN: BIp/GWN871rp7Oj2E4WOYWrhGbzfey4Xaca/EOt+7mbNHgC8DQ9bijHY4OHO+aRCWTg0nwdM0imba2qXqoTzu4oRnzo6lJ8Tgh0hxeOFoA+DXR850We3GxHbKDEcLCRptI4TwzHFWO1BBPcmjtqhGzNj82n6MXsQdNOsaDNByYVFCfYXHlsopodVx8tr0rkftMM2jpJf/tkrM3XQpBZQaRngEfkAJzRksLr64CGUdGhtWVt/jHI7THVp+ji7x/M6dc2IEZ4AbV5dLGVnZjhrpf9kI0PNE9QVqWM3VMWSrXkAAPPhSJ1R8cnRF+zxd7PhkIHpmjSzERVrRK2AgA9C8Zeu7o4UplTfp8wE85eWRkKY7up/vPvdDE7V8rVJ3EmlubIwkCYlWU6ISD72ErcD5SIzv6DE+8J70fkPyIguo1LaePRbKPdtjaZmTY1qiaFfk4AtSZjjG6mJjQkY0U6uWRQb4gz/JVM+LaA3ldBTmx5DqHfjYl5AVGerC5Sk0kkY10tTHEjYHyYOqPnBeuFrTc31AHLdbFGlcB2oAt6myuPkBCLNFA+tdBBvM4A2YZ8Hofm/WVFlzdfHLD9kV7IeuA2Fr/5PwXrwZdNI/bP5Yu9s9oa/KdCwj8lLa8q8ZOhHNH2R3sBw6pACBx+njuFV6Xi1hXnP28UgMSsehDdw1jk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
